tools/plugin-release
Cleaned files may be referenced in composer autoloader classmap and can lead to errors like this:
```
[2020-04-06 08:02:16] glpiphplog.WARNING:   *** PHP Warning (2): include(C:\laragon\www\glpi\9.5.git\marketplace\barcode\vendor\composer/../pear/pear/tests/PEAR_Command_Install/bundle/packages/Archive_Tar/Archive/Tar.php): failed to open stream: No such file or directory in C:\laragon\www\glpi\9.5.git\vendor\composer\ClassLoader.php at line 444
Backtrace :
vendor\composer\ClassLoader.php:444                include()
vendor\composer\ClassLoader.php:322                Composer\Autoload\includeFile()
:                                                  Composer\Autoload\ClassLoader->loadClass()
:                                                  spl_autoload_call() …
```
=> Fix missing test classes in classmap

tools/plugin-release
Fix error `subprocess.CalledProcessError: Command '['git', 'ls-tree', '-r', 'my-custom-version', '--name-only']' returned non-zero exit status 128.` returned when calling `vendor/bin/plugin-release --verbose --assume-yes --nogithub --dont-check --release my-custom-version --extra prerelease --commit 5f63f89`
1. `git ls-tree` must use commit if forced by command options.
2. `ls_files_cmd` was not used anymore.
=> Fix release build when using --commit option

tools/plugin-release
I also change a bit the way composer is called to install composer dependencies even if lock file is not present.
=> Call npm install if package.json exists

README.md, github-actions/build-package/Dockerfile, github-actions/build-package/README.md, github-actions/build-package/action.yml, github-actions/build-package/entrypoint.sh, tools/plugin-release
This action can be used to build a plugin's release package.
Example of test run that sucessfully created a release and its package: https://github.com/cedric-anne/glpi-plugin-credit/runs/1711133627?check_suite_focus=true
=> Plugin package building Github action

composer.json
Robo API has no real BC-breaks, except support of some PHP / symfony versions.
Robo 1.x is for PHP < 7.1, so we can drop it.
Robo 3.x officially supports PHP 8.0, even if I did not find any problem for now on this PHP version.
=> Enable usage of Robo 3.x, drop usage of Robo 1.x

composer.json, src/Tools/RoboFile.php, tools/plugin-release
Minification tasks are disabled and there is no alternative using PHP.
Minification can be done using a nodejs script on npm `postinstall` event, as the plugin-release script calls `npm install` command when a `package.json` file is detected.
=> Remove disabled minification tasks

src/Tools/LicenceHeadersCheckCommand.php
CSSO is one of the most used CSS optimizer. During CSS minification, it only preserves comments starting with `/*!`.
This PR introduces 2 changes :
- prepended line on CSS files will now be `/*!`;
- headers content checking will now ignore prepended and appended lines (i.e. lines reserved to comment opening and comment closing), in order to not consider all existing headers as invalid in CSS files.
=> Handle CSSO preserved comments

tools/plugin-release
Fixes SyntaxWarning logged during plugin release.
=> FIx "is not" with literal SyntaxWarning

composer.json
We will soon move to PSR-12 in GLPI, and, as we get closer to the standards, having a package defining code rules shared with plugins makes less and less sense. Indeed, some plugins may want to keep old rules, to prevent huge styling changes on codebase, while other may want to use more strict rules than GLPI does. Thus, most of plugins does not even have an automated lint job.
I propose to remove glpi-project/coding-standard dependency from here and let everyone specify its own ruleset. IMHO, it will be easier to maintain, as we will not have to create a `glpi-project/coding-standard` release, then a `glpi-project/tools` release, then a `composer update glpi-project/tools -w` everytime we want to change the ruleset.
=> Remove glpi-project/coding-standard dependency

src/Tools/LicenceHeadersCheckCommand.php
PSR-12 requires an empty line before header blocks, like this:
```php
<?php
/**
* Licence header....
*/
```
With this PR, if there are lines before licence headers, they will be separated from them by an empty line.
Empty lines are not taken into account during check, so it should not have any impact on check results.
=> Fix PSR-12 compliance

src/Tools/LicenceHeadersCheckCommand.php
Sometimes, the last line of licence headers may contains something else than spacing chars, and, in such a case, header ending is not detected, and the whole file content may be considered as current licence header.
For instance, following header ending was not detected:
```php
<?php
/*
---------------------
HEADER....
--------------------- */
```
=> Fix licence header ending detection

bin/extract-locales
Recently, composer changed the way to handle packages binaries. They were previously deployed via a symlink, but are now deployed using a proxy script. It changes the execution path retrieved by `$0`.
=> Fix locales extract from proxified binary

bin/compile-twig-templates, bin/extract-locales, composer.json, src/Tools/CompileTwigTemplatesCommand.php
Alternative to #46 .
All twig templates are compiled into PHP files and saved a temporary directory, then PHP files are processed to extract strings.
Compilation does not require usage of GLPI or any GLPI plugin code, in order to prevent compatibility issues with future GLPI versions.
Logic has been made to preserve filenames in POT file comments, but line numbers cannot be preserved as it is nearly impossible to retrieve line number in source template from compiled line number.
Updated POT file example:
```diff
-#: templates/components/itilobject/fields_panel.html.twig:312
+#: templates/components/itilobject/fields_panel.html.twig
#: src/NotificationTargetProblem.php:200 src/Problem.php:502
msgid "Causes"
msgstr "Causes"
```
=> Fix locales extract from twig templates

github-actions/build-package/entrypoint.sh
Since latest version of git, the `build-package` action is broken. Indeed, UID used in different actions is not always identical, and it triggers git errors.
I guess we can consider the current directory as safe, as we will only use git on it to fetch/list tags.
```
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
Traceback (most recent call last):
File "/github/workspace/vendor/glpi-project/tools/tools/plugin-release", line 754, in <module>
Namespace(release='2.10.2', nogithub=False, check_only=False, dont_check=True, propose=False, commit=None, extra=None, compile_mo=False, nosign=False, assume_yes=True, verbose=True, f=False)
Building …
```
=> Prevent unsafe git dir exception

src/Tools/LicenceHeadersCheckCommand.php
Some files may contains additionnal data in their licence header, for instance, an additionnal copyright.
With this PR, additionnal data defined using tags (e.g. `@copyright 2010-2022 Another team`)  will be preserved, unless `--discard-extra-tags` option is used. Also, presence of this addtionnal data will not result in considering file header as outdated.
There is also 2 fixes for GLPI core:
- `bin/*` files are now checked,
- `lib/bundles/*` and `lib/index.php` files are now checked.
=> Add ability to preserve tagged data in licence headers

bin/compile-twig-templates, bin/extract-locales, bin/licence-headers-check, github-actions/build-package/Dockerfile, github-actions/build-package/action.yml, github-actions/build-package/entrypoint.sh, src/Tools/CompileTwigTemplatesCommand.php, src/Tools/LicenceHeadersCheckCommand.php, tools/plugin-release
License headers were missing or copy/pasted from GLPI.
I added/fixed them, using the GPLv3+.
For the release script, I added a `@copyright 2012-2017 The Galette Team`.
=> Fix license headers

bin/extract-locales
`find` command does not have a `-regextype` option on `alpine`, and is only compatible with [`posix-basic`](https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dbasic-regular-expression-syntax.html) syntax.
On other distributions we mainly use, `find` command uses [`emacs`](https://www.gnu.org/software/findutils/manual/html_node/find_html/emacs-regular-expression-syntax.html) syntax by default.
Unlike [`posix-egrep`](https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002degrep-regular-expression-syntax.html) syntax, on both `posix-basic` an `emacs`, grouping operators ( `(` and `)`) and alternation operator (`|`) have to be backslashed.
=> Fix extract-template command on alpine linux context

composer.json
This is required t be able to upgrade symfony/console to 6.x in GLPI.
=> Symfony 6.x compatibility

src/Tools/LicenceHeadersCheckCommand.php
With this PR, licence header template file can be placed in `.licence-header` in root directory of the project. It will permit to easilly keep this file in GLPI archive even after `tools` directory removal. Thus, in most plugins, it will permit to not have a `tools` directory that often contains only this file.
=> Search for licence header template file in .licence-header

bin/extract-locales
`xgettext` command will fail if there is no file to process.
For instance, on plugin a have no `.js` files, following error occurs:
```
$ ./vendor/bin/extract-locales 
xgettext: no input file given
Try 'xgettext --help' for more information.
```
=> Prevent locale extract from failing when some files types are not existing

src/Tools/LicenceHeadersCheckCommand.php
Hidden files are excluded from release archives and are likely to not contains anything that should be protected by a licence. They usually are config files.
See https://github.com/glpi-project/glpi/pull/14942. We had to add licence headers in `docker-compose.yml` file.
=> Exclude all hidden files from licence headers checks

github-actions/build-package/entrypoint.sh
Fixes the following deprecation:
=> Replace deprecated usage of `::set-output`

src/LicenceHeadersCheckCommand.php
The copyright tags unduplicate logic in the licence headers update command was not correctly handling the following case:
- no text between `@copyright` tag and dates (e.g. `@copyright 2015-2025 Teclib' and contributors.`)
- no text between dates and the end of `@copyright` tag line (e.g. `@copyright Teclib' and contributors 2015-2025`)
On GLPI, without this fix, it would generate duplicated tag, e.g.
```
* @copyright 2015-2024 Teclib' and contributors.
* @copyright 2003-2014 by the INDEPNET Development Team.
* @copyright 2015-2023 Teclib' and contributors.
```
In https://github.com/glpi-project/glpi/pull/16293, the `--discard-extra-tags` option was used to bypass this, but I figured out later that it has deleted extra tags that I had to put back (see …
=> Fix copyright unduplicate logic

src/CompileTwigTemplatesCommand.php
In Twig 3.12+, callables validity are checked. Therefore, we cannot longer use fake callables like `'get_plural_number'` that is not a valid global function.
Fixes the following error:
```
+ vendor/bin/extract-locales
+ tee extract.log
In Environment.php line 556:
An exception has been thrown during the compilation of a template ("Callbac  
k for function "get_plural_number" is not callable in the current scope.")   
in "dropdown_form.html.twig".                                                
In ReflectionCallable.php line 47:
Callback for function "get_plural_number" is not callable in the current sc  
ope.                                                                         
In ReflectionCallable.php line 45:
Failed to create closure from callable: function "get_plural_number" not …
```
=> Fix compatibility with Twig 3.12

tools/plugin-release
We had an issue with a plugin that has a vendor file with a path greater than 100 chars. It seems to be a PHP bug, see https://github.com/php/php-src/issues/19311
Python uses the `pax`/`posix` format by default since version 3.8. Switching back to the `ustar` format fixes the issue. The `ustar` format limitations should not be an issue, see https://www.gnu.org/software/tar/manual/html_section/Formats.html
=> Bypass plugin archive path limitation by using the USTAR tar format

bin/compile-twig-templates
fix #80 
Functions are missing when extracting locales for a plugin under GLPI 11. 
Enclosed in a if () statement as the functions are already defined when running for GLPI 11 (core).
=> fix undeclared functions in plugin context for GLPI 11
